version: '2'

networks:
  default-network:
    driver: bridge

services:
  rabbitmq:
    container_name: rabbitmq
    ports:
      - 127.0.0.1:15672:15672
      - 127.0.0.1:5672:5672
    environment:
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_USER=admin
    tty: true
    image: rabbitmq:3.6-management
    stdin_open: true
    networks:
      - default-network
